/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user account and receive access & refresh tokens
         * @description Registers a new user, hashes password, and issues initial access and refresh tokens.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with email & password to receive access & refresh tokens
         * @description Authenticates credentials and returns a 15-minute access token + 7-day refresh token.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token and issue a fresh access token
         * @description Refresh Token Rotation:
         *     Accepts an existing refresh token, verifies it in the DB, revokes it, and issues
         *     a new 15-minute access token and a new 7-day refresh token.
         */
        post: operations["refresh_tokens_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the refresh token on user logout
         * @description Revokes the refresh token in PostgreSQL to prevent further session renewals.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user profile
         * @description Returns the profile of the currently authenticated user.
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/upload-resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload and parse a resume document (PDF)
         * @description Upload a candidate resume PDF, extract text in-memory, and use Gemini to
         *     synthesize a strictly typed ParsedProfile object.
         *     Optionally saves the candidate profile and ingests bullets into pgvector.
         */
        post: operations["upload_and_parse_resume_api_profile_upload_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or update candidate profile
         * @description Persist or update candidate profile info in the relational database.
         */
        post: operations["save_profile_api_profile_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve candidate profile
         * @description Fetch candidate profile for the authenticated tenant and user.
         */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/bullets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all master bullets
         * @description Retrieve all master bullets associated with the current tenant and user.
         */
        get: operations["list_bullets_api_profile_bullets_get"];
        put?: never;
        /**
         * Add and embed master bullets
         * @description Add new master bullets to the candidate vault and synchronize their
         *     embeddings into pgvector with tenant/user isolation.
         */
        post: operations["add_bullets_api_profile_bullets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/analyze-jd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze target Job Description
         * @description Extract key requirements, technical skills, core responsibilities,
         *     and ATS keywords from a raw Job Description.
         */
        post: operations["analyze_jd_endpoint_api_resume_analyze_jd_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate ATS-tailored resume via RAG pipeline
         * @description Full end-to-end RAG Resume Tailoring Pipeline delegated to resume_service:
         *     1. Analyzes the target Job Description.
         *     2. Retrieves top-K matching candidate achievements via pgvector with multi-tenant isolation.
         *     3. Fetches candidate base profile.
         *     4. Synthesizes tailored resume in structured JSON and LaTeX using STAR format.
         *     5. Calculates objective ATS match score and keyword gap analysis.
         *     6. Persists the tailored resume record in the database.
         */
        post: operations["tailor_resume_endpoint_api_resume_tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve candidate generated resumes history
         * @description List all previously generated tailored resumes for the tenant and user.
         */
        get: operations["get_resume_history_api_resume_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a specific tailored resume
         * @description Fetch a specific tailored resume by ID with tenant verification.
         */
        get: operations["get_resume_by_id_api_resume__resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_and_parse_resume_api_profile_upload_resume_post */
        Body_upload_and_parse_resume_api_profile_upload_resume_post: {
            /** File */
            file: string;
        };
        /**
         * CertificationItem
         * @description Professional certification record.
         */
        CertificationItem: {
            /** Name */
            name: string;
            /** Issuer */
            issuer: string;
            /** Issue Date */
            issue_date?: string | null;
            /** Credential Url */
            credential_url?: string | null;
        };
        /**
         * EducationItem
         * @description Academic degree / institution record.
         */
        EducationItem: {
            /** Institution */
            institution: string;
            /** Degree */
            degree: string;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Start Year */
            start_year?: string | null;
            /** End Year */
            end_year?: string | null;
            /** Gpa */
            gpa?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JDAnalysis
         * @description Structured extraction of target job description requirements via Gemini.
         */
        JDAnalysis: {
            /** Job Title */
            job_title: string;
            /** Company */
            company?: string | null;
            /**
             * Primary Skills
             * @default []
             */
            primary_skills: string[];
            /**
             * Core Responsibilities
             * @default []
             */
            core_responsibilities: string[];
            /**
             * Keywords To Target
             * @default []
             */
            keywords_to_target: string[];
            /** Seniority Level */
            seniority_level?: string | null;
        };
        /**
         * JDAnalysisRequest
         * @description Payload to request automated analysis of a job description.
         */
        JDAnalysisRequest: {
            /** Job Description */
            job_description: string;
            /** Job Title */
            job_title?: string | null;
            /** Company */
            company?: string | null;
        };
        /**
         * MasterBulletCreate
         * @description Payload to create a new quantified achievement / master bullet point.
         */
        MasterBulletCreate: {
            /** Bullet Text */
            bullet_text: string;
            /**
             * Skills Used
             * @default []
             */
            skills_used: string[];
            /**
             * Category
             * @default Work Experience
             */
            category: string;
            /** Project Name */
            project_name?: string | null;
            /** Impact Metrics */
            impact_metrics?: string | null;
            /** Experience Id */
            experience_id?: string | null;
        };
        /**
         * MasterBulletResponse
         * @description Master bullet response from database.
         */
        MasterBulletResponse: {
            /** Bullet Text */
            bullet_text: string;
            /**
             * Skills Used
             * @default []
             */
            skills_used: string[];
            /**
             * Category
             * @default Work Experience
             */
            category: string;
            /** Project Name */
            project_name?: string | null;
            /** Impact Metrics */
            impact_metrics?: string | null;
            /** Experience Id */
            experience_id?: string | null;
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MessageResponse
         * @description Standard generic success message response.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * ParsedExperienceItem
         * @description Work experience item extracted from a candidate resume.
         */
        ParsedExperienceItem: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Duration */
            duration?: string | null;
            /** Location */
            location?: string | null;
            /**
             * Bullet Points
             * @default []
             */
            bullet_points: string[];
            /**
             * Skills Used
             * @default []
             */
            skills_used: string[];
        };
        /**
         * ParsedProfile
         * @description Output schema for resume document (PDF/DOCX) extraction via Gemini.
         */
        ParsedProfile: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
            /** Portfolio */
            portfolio?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Education
             * @default []
             */
            education: components["schemas"]["EducationItem"][];
            /**
             * Experiences
             * @default []
             */
            experiences: components["schemas"]["ParsedExperienceItem"][];
            /**
             * Projects
             * @default []
             */
            projects: components["schemas"]["ProjectItem"][];
            /**
             * Certifications
             * @default []
             */
            certifications: components["schemas"]["CertificationItem"][];
        };
        /**
         * ProfileCreate
         * @description Payload to create or initialize a candidate profile.
         */
        ProfileCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Github Url */
            github_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Education
             * @default []
             */
            education: {
                [key: string]: unknown;
            }[];
            /**
             * Certifications
             * @default []
             */
            certifications: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ProfileResponse
         * @description Complete candidate profile response from database.
         */
        ProfileResponse: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Github Url */
            github_url?: string | null;
            /** Portfolio Url */
            portfolio_url?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Education
             * @default []
             */
            education: {
                [key: string]: unknown;
            }[];
            /**
             * Certifications
             * @default []
             */
            certifications: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectItem
         * @description Portfolio / personal project entry.
         */
        ProjectItem: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Technologies
             * @default []
             */
            technologies: string[];
            /**
             * Bullet Points
             * @default []
             */
            bullet_points: string[];
            /** Link */
            link?: string | null;
        };
        /**
         * RefreshTokenRequest
         * @description Payload to request a new access token using a refresh token.
         */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RefreshTokenResponse
         * @description Payload returned upon refreshing tokens.
         */
        RefreshTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * SynthesizedExperience
         * @description Experience item tailored specifically to target JD keywords.
         */
        SynthesizedExperience: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Duration */
            duration?: string | null;
            /** Location */
            location?: string | null;
            /** Tailored Bullets */
            tailored_bullets: string[];
        };
        /**
         * TailorRequest
         * @description Request payload to initiate AI RAG tailoring pipeline.
         */
        TailorRequest: {
            /**
             * Job Description
             * @description Full job description text
             */
            job_description: string;
            /**
             * Target Job Title
             * @description Target job title override
             */
            target_job_title?: string | null;
            /**
             * Top K Bullets
             * @description Top-K bullets to retrieve via pgvector RAG
             */
            top_k_bullets?: number | null;
            /**
             * Master Bullets
             * @description Direct bullets override bypassing RAG retrieval
             */
            master_bullets?: string[] | null;
        };
        /**
         * TailoredResumeContent
         * @description Full structured JSON representation of a synthesized tailored resume.
         */
        TailoredResumeContent: {
            /** Candidate Name */
            candidate_name: string;
            /** Contact Info */
            contact_info: {
                [key: string]: string | null;
            };
            /** Professional Summary */
            professional_summary: string;
            /** Highlighted Skills */
            highlighted_skills: string[];
            /** Experiences */
            experiences: components["schemas"]["SynthesizedExperience"][];
            /**
             * Projects
             * @default []
             */
            projects: {
                [key: string]: unknown;
            }[];
            /**
             * Education
             * @default []
             */
            education: {
                [key: string]: unknown;
            }[];
            /**
             * Certifications
             * @default []
             */
            certifications: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TailoredResumeModelResponse
         * @description Database record response for a saved tailored resume.
         */
        TailoredResumeModelResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
            /** Jd Id */
            jd_id?: string | null;
            /** Title */
            title: string;
            /** Structured Content */
            structured_content: {
                [key: string]: unknown;
            };
            /** Raw Latex */
            raw_latex?: string | null;
            /** Match Score */
            match_score?: number | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TailoredResumeResponse
         * @description Final synthesized resume response with ATS match score and LaTeX.
         */
        TailoredResumeResponse: {
            /** Id */
            id?: string | null;
            /** Job Title */
            job_title: string;
            /** Match Score */
            match_score?: number | null;
            /**
             * Matched Keywords
             * @default []
             */
            matched_keywords: string[];
            /**
             * Missing Keywords
             * @default []
             */
            missing_keywords: string[];
            structured_resume: components["schemas"]["TailoredResumeContent"];
            /** Latex Source */
            latex_source?: string | null;
        };
        /**
         * Token
         * @description JWT response returned upon successful authentication (Access + Refresh).
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Tenant Id */
            tenant_id: string;
            /** User Id */
            user_id: string;
            user?: components["schemas"]["UserResponse"] | null;
        };
        /**
         * UserCreate
         * @description Payload required to register a new user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Tenant Id
             * @description Tenant ID for multi-tenant isolation
             * @default default_tenant
             */
            tenant_id: string;
            /**
             * Password
             * @description User raw password (will be hashed)
             */
            password: string;
        };
        /**
         * UserLogin
         * @description Payload required for user authentication.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Tenant Id
             * @default default_tenant
             */
            tenant_id: string;
        };
        /**
         * UserResponse
         * @description Public user response object.
         */
        UserResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Tenant Id
             * @description Tenant ID for multi-tenant isolation
             * @default default_tenant
             */
            tenant_id: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tokens_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    upload_and_parse_resume_api_profile_upload_resume_post: {
        parameters: {
            query?: {
                /** @description Whether to immediately persist extracted profile and embed bullets in pgvector */
                save_to_db?: boolean;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_and_parse_resume_api_profile_upload_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_api_profile_save_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bullets_api_profile_bullets_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterBulletResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_bullets_api_profile_bullets_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasterBulletCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterBulletResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_jd_endpoint_api_resume_analyze_jd_post: {
        parameters: {
            query?: {
                /** @description Persist target JD in database */
                save_jd?: boolean;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JDAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JDAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tailor_resume_endpoint_api_resume_tailor_post: {
        parameters: {
            query?: {
                /** @description Persist synthesized resume in DB */
                save_to_db?: boolean;
            };
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TailorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TailoredResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_history_api_resume_history_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TailoredResumeModelResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_by_id_api_resume__resume_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-ID"?: string | null;
                "X-User-ID"?: string | null;
            };
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TailoredResumeModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
